### PR TITLE
Assume so test is reported is as skipped rather than passed on JDK 13+

### PR DESCRIPTION
**Pull request by elharo**

### CODE REVIEW

**Review by michael-o — APPROVED** [review]

**Review by slachiewicz — APPROVED** [review]

**Comment by elharo** [comment]
The CI seems to be treating AssumptionViolatedException as a failure:

```
org.junit.AssumptionViolatedException: got: <false>, expected: is <true>
	at org.junit.Assume.assumeThat(Assume.java:106)
	at org.junit.Assume.assumeTrue(Assume.java:50)
	at org.apache.maven.plugins.javadoc.JavadocReportTest.testDoclets(JavadocReportTest.java:480)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
```

**Comment by pzygielo** [comment]
> The CI seems to be treating AssumptionViolatedException as a failure:

Not only CI, I'm getting the same locally. Don't you?

Next part of stacktrace (skipped above) gives clue:
```
...
	at junit.framework.TestCase.runTest(TestCase.java:177)
	at junit.framework.TestCase.runBare(TestCase.java:142)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
```

Just guessing that it is related to `AbstractMojoTestCase` being `junit.framework.TestCase` (JUnit3). I'm unsure if assumptions were ported to JUnit 3.

**Comment by elharo** [comment]
No, I don't. I see it skip locally.

**Comment by pzygielo** [comment]
> No, I don't. I see it skip locally.

Do you use maven/surefire to execute this test, or rather some IDE with its runner?

**Pull request closed without merging**
