### PR TITLE
[MJAVADOC-444] add aggregate-no-fork and aggregate-test-no-fork for non-forking versions of aggregate goals.

### PR DESCRIPTION
**Pull request by busbey**
Follows the same pattern as JavadocNoForkReport with the aggregate goals.

Tested out locally by installing a SNAPSHOT version and then moving my project over to it.

### CODE REVIEW

**Comment by abudaev** [comment]
Can you release with goal ASAP?)

**Comment by busbey** [comment]
@abudaev this change hasn't been merged into the project source yet, so it's unlikely to be in a release in the short term.

For more info, esp to watch for updates, I'd recommend subscribing to [MJAVADOC-444](https://issues.apache.org/jira/browse/MJAVADOC-444) on the project JIRA.

**Comment by abudaev** [comment]
@busbey maybe you how to fix this trouble ->

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.1.0:single (create distr) on project aggragator-module: Failed to create assembly: Error adding file 'javadoc-aggragate:module1:jar:1.0-SNAPSHOT' to archive: \trouble\module1\target\classes isn't a file. -> [Help 1]

example project structure 
https://github.com/abudaev/trouble
mvn verify -P parrent-module

**Comment by busbey** [comment]
Hi @abudaev!

Your best bet is to bring the issue up on the [users@maven mailing list](https://lists.apache.org/list.html?users@maven.apache.org) or open a new issue with the details.

**Comment by khmarbaise** [comment]
@busbey Hi, can you please remove the `@version $Id$` entries from your file...

**Comment by khmarbaise** [comment]
So now I try to see what our CI says...

**Comment by khmarbaise** [comment]
So unfortunately the CI build has failed please take a detail look here: https://builds.apache.org/view/M-R/view/Maven/job/maven-box/job/maven-javadoc-plugin/job/MJAVADOC-444/1/console

**Comment by jira-importer** [comment]
Resolve #737

**Comment by jira-importer** [comment]
Resolve #737

**Pull request merged**
