### PR TITLE
[MJAVADOC-799] Remove inconsistent `AbstractFixJavadocMojo#defaultVersion` default value

### PR DESCRIPTION
**Pull request by Marcono1234**
As mentioned in [MJAVADOC-799](https://issues.apache.org/jira/browse/MJAVADOC-799) there is currently a mismatch for the `AbstractFixJavadocMojo#defaultVersion` parameter default value:
- documented value: `$Id:$`
- initial field value: `$Id: $`
- `@Parameter#defaultValue`: `$Id: $Id`

It seems `@Parameter#defaultValue` overwrites the initial field value. This can be seen when running `mvn org.apache.maven.plugins:maven-javadoc-plugin:3.7.0:fix` on a dummy project; it will add `@version $Id: $Id` to the Javadoc.

As mentioned in the Jira issue I am not sure if `$Id: $Id` is really a good / the intended default value, but it is the value currently used by the Mojo, therefore I have kept it. And I have adjusted the expected unit test results because they don't seem to create the Mojo instance the way Maven normally does, and are therefore using the initial field value (which was previously incorrect) instead of `@Parameter#defaultValue`.

I have also included some small changes for URLs and `defaultValue` for other parameters. Please let me know if I should omit that because it is not directly related to this.

----

Following this checklist to help us incorporate your
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MJAVADOC) filed
       for the change (usually before you start working on it).  Trivial changes like typos do not
       require a JIRA issue.  Your pull request should address just this issue, without
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MJAVADOC-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MJAVADOC-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify -Prun-its` to make sure basic checks pass. A more thorough check will
       be performed on your pull request automatically.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by michael-o** [comment]
Since the value cannot be reasonably set to empty I would drop the default value, it has no use at all.

**Review by michael-o — APPROVED** [review]

**Comment by Marcono1234** [comment]
Thanks for the adjustments! It seems currently no test covers a custom `defaultVersion` value, unless I am overlooking something. Should I create a follow-up pull request and adjust the unit test or the integration test to use a custom value?

**Comment by michael-o** [comment]
> Thanks for the adjustments! It seems currently no test covers a custom `defaultVersion` value, unless I am overlooking something. Should I create a follow-up pull request and adjust the unit test or the integration test to use a custom value?

That's be great. Currently, we cover that there is no default value for `defaultVersion`. Now we need a test with a custom version set and that the version truly arrives in the modified files.

**Comment by Marcono1234** [comment]
Have created #305 for adding a test.

**Comment by jira-importer** [comment]
Resolve #1178

**Pull request merged**
